### ISSUE TITLE
I am having problems with it while storing jokes in a variable

### ISSUE THREAD

**Issue by MojizTheGameDev** [pyjokes/pyjokes#100]
I want to store the every joke that generates in to one variable and then I don't want to print it, instead, I want send jokes in my discord server using my bot (discord.py package), also, is this project abandoned? Help me!!

**Comment by bennuttall** [comment]
```python
import pyjokes

joke = pyjokes.get_joke()
```

> also, is this project abandoned?

Sadly, one of the pyjokes maintainers passed away last year. We haven't been maintaining the library for a while but will get around to tidying up  when we get chance.

https://www.europython-society.org/farewell-to-oier-echaniz-beneitez/

**Comment by MojizTheGameDev** [comment]
Soo sad to that he passed away :(   No problem bro, you can work after getting chance
