### ISSUE TITLE
pyjokes: command not found

### ISSUE THREAD

**Issue by bennuttall** [pyjokes/pyjokes#11]
You install a package called `pyjokes` then you might expect to run `pyjokes` at the command line. However, currently this returns the error `pyjokes: command not found` because the correct command is `pyjoke`.

This usage makes sense as `pyjoke` yields a single joke. However, this could be confusing.

I propose three options:

1. We rename the script to `pyjokes`
2. We alias `pyjokes` to `pyjoke`
3. We leave `pyjoke` as is, and add a `pyjokes` script to say "Did you mean pyjoke?"

Thoughts?

**Comment by ljsalvatierra** [comment]
Personally I would choose the 2nd option (alias).

**Comment by bennuttall** [comment]
Added third option, my preference:

> We leave pyjoke as is, and add a pyjokes script to say "Did you mean pyjoke?"

**Comment by ljsalvatierra** [comment]
I like the 3rd option also, If you prefer it go for it, :+1:

**Comment by alexsavio** [comment]
I did it already. LGTM :P
