### ISSUE TITLE
Jokes not funny!!!😡👎💩

### ISSUE THREAD

**Issue by dvzadara** [pyjokes/pyjokes#116]
There are lot of not funny jokes!😭

My cringe top 8:

1. If you play a Windows CD backwards, you'll hear satanic chanting ... worse still, if you play it forwards, it installs Windows.👎
2. How many programmers does it take to kill a cockroach? Two: one holds, the other installs Windows on it.💩
3. Speed Kills! Use Windows.🤦‍♂️
4. The box said: 'install on Windows 95, NT 4.0 or better'. So I installed it on Linux.🤡
5. Windows is NOT a virus. Viruses DO something.🤦‍♀️
6. WINDOWS stands for Will Install Needless Data On Whole System.☠️
7. Bugs come in through open Windows.😡
8. Computers are like air conditioners: they stop working when you open Windows.🤥

Replace this to Chuck Norris please.

**Comment by alexsavio** [comment]
I am sorry but I cannot reproduce the issue, it works on my Windows machine
and the tests are passing.

Could you please give us more details?

Thank you.
