### ISSUE TITLE
ModuleNotFoundError for pyjokes Despite Installation

### ISSUE THREAD

**Issue by Onkar86** [pyjokes/pyjokes#129]
I am encountering a ModuleNotFoundError when trying to use the pyjokes library in my Python script, even though pyjokes is installed in my environment. Here are the details of my setup and the steps I have taken to troubleshoot the issue.

Environment:

Operating System: Windows 11
![Screenshot 2024-07-15 100751](https://github.com/user-attachments/assets/9e1656de-e811-421a-a133-a6ac62c11e80)

Python Version: 3.12
pyjokes Version: 0.7.2
IDE: [Specify if using any, e.g., VS Code, PyCharm]
Steps to Reproduce:

Install pyjokes using pip:

sh
Copy code
pip install pyjokes
Verify installation:

sh
Copy code
pip list
Output shows pyjokes installed:

Copy code
pyjokes 0.7.2
Create a Python script (module.py):

python
Copy code
import pyjokes

def main():
    joke = pyjokes.get_joke()
    print(joke)

if __name__ == "__main__":
    main()
Run the script:

sh
Copy code
python module.py
Observed Behavior:

I receive the following error message:
arduino
Copy code
Exception has occurred: ModuleNotFoundError
No module named 'pyjokes'
Additional Details:

I have verified that pyjokes is installed in the correct Python environment.
I have tried reinstalling pyjokes using pip uninstall pyjokes followed by pip install pyjokes.
I have ensured that the script is being run in the same environment where pyjokes is installed.
I attempted to activate a virtual environment and install pyjokes within it, but encountered an issue activating the virtual environment with the following error:
csharp
Copy code
.\venv\Scripts\activate : The term '.\venv\Scripts\activate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Expected Behavior:

The script should run without errors and print a joke from the pyjokes library.
Request:

Any guidance or suggestions on resolving this issue would be greatly appreciated. If there are specific environment configurations or additional steps I should take, please let me know.
Thank you for your assistance!
![Screenshot 2024-07-15 100751](https://github.com/user-attachments/assets/bc5d5b9e-e6e9-40d8-8ce5-34a2530ddc1b)
![Screenshot 2024-07-15 101322](https://github.com/user-attachments/assets/698a9c16-2d15-462c-94a3-a32902df3470)
![Screenshot 2024-07-15 100751](https://github.com/user-attachments/assets/bfca39e4-4108-45e0-8e18-76e4520e27f2)
![Screenshot 2024-07-15 101322](https://github.com/user-attachments/assets/388369e3-f0e8-4449-a1d1-e8fa5ec08ad2)
![Screenshot 2024-07-15 101413](https://github.com/user-attachments/assets/d2fcdef4-197a-43e6-930a-10a665e286d1)

**Comment by bennuttall** [comment]
I tested this on Windows and vscode and it works fine:

![pyjokes](https://github.com/user-attachments/assets/c720f579-6fbf-4e5f-8c7b-dae0dd9475dd)

You must have not installed it into the environment vscode is using.

I ran `pip install pyjokes` in a command prompt.
