### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by bennuttall** [pyjokes/pyjokes#13]
@oiertwo where are the tests? They should be runnable locally (i.e. before commit, not after) and stored in a `tests` directory in the project root.

I have some suggestions for more tests:

- Test all jokes are 140 characters or less
- Test error is appropriate for command line near-miss (i.e. `pyjokes`)
- Test errors are appropriate for language not available in Python and on command line (e.g. `pyjokes -l eu`)

(others: please add other wanted test cases here)

**Comment by oiertwo** [comment]
Test are in branch tests, folder tests and they are runnable locally before commit, with command "python setup.py test" it will work if pytest is installed. 

I will add your test to the library as soon as I have some time :).

**Comment by bennuttall** [comment]
Resolved with #16
