### ISSUE TITLE
`explicit` should be called `adult`

### ISSUE THREAD

**Issue by alexsavio** [pyjokes/pyjokes#15]
I guess there is no such thing as an `explicit joke`, all jokes should be explicit, otherwise nobody would be able to transmit them. A sentence could have an `implicit` joke, but that I guess is called irony.
Shouldn't we call `adult` instead of `explicit`?

**Comment by bennuttall** [comment]
Explicit is better than implicit.

**Comment by bennuttall** [comment]
I guess you're right

**Comment by alexsavio** [comment]
Can I modify it?

Alexandre Manhães Savio [image: cid:part1.05060801.02000507@gmail.com]
<http://scholar.google.es/citations?user=h_jN_q4AAAAJ&hl=en>
PhD, Medical Imaging, Machine Learning
ENGINE Project <http://engine.pwr.wroc.pl> Wrocław University of Technology
home <http://alexsavio.github.io/> | email: alexsavio@gmail.com

**Comment by bennuttall** [comment]
Go ahead!

**Comment by bennuttall** [comment]
Fixed with PR #18
