### ISSUE TITLE
How about adding Jokes Guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by yashmehrotra** [pyjokes/pyjokes#21]
We can add some common stuff like:
 - Jokes should be gender neutral.
 - Racism should be avoided.
 - Jokes that are abusive, hateful, pornographic, unlawful, libelous, or that discriminate against or disrespect people’s ethnicity, gender, sexual orientation, religious belief, age or disability should be avoided.
 - Etc.

**Comment by bennuttall** [comment]
Good idea

**Comment by yashmehrotra** [comment]
@bennuttall Lets curate a list of all this and the points we can think of to this thread. Then I will add the guidelines to the file.

**Comment by alexsavio** [comment]
Well, it is not that 'jokes should gender neutral'. There is a comment on the wiki: https://github.com/pyjokes/pyjokes/wiki. We could remove it and put everythin in CONTRIBUTING.md
The rest of your list, @yashmehrotra looks good. 
I would say that jokes:
[x] must be less than 140 characters long,
[x] must be gender neutral if the gender is not important for the sense of the joke, taking into account that
[x] jokes that are abusive, hateful, pornographic, unlawful, libelous, or that discriminate against or disrespect people’s ethnicity, gender, sexual orientation, religious belief, age or disability, etc. will not be accepted

**Comment by alexsavio** [comment]
Well, there is a few jokes about fat people, like:
"Your momma's so fat that not even Dijkstra is able to find a shortest path around her."
This is not gender neutral and is not respectful to the obese. :/
What should we do?

**Comment by yashmehrotra** [comment]
@alexsavio Since **Yo Mamma** is a popular joke category, I don't think any one will be offended. And fat and female are the basis of the joke category, so according to me it should remain there.
By `Jokes should be gender neutral.` , I meant jokes should be gender neutral as long as it doesnt take the punchline away, if the joke is offensive in that manner, we can even make a new `offensive` category

**Comment by alexsavio** [comment]
I agree with you @yashmehrotra. The `offensive` category shouldn't be part of pyjokes. I guess we can make humour without offending anyone, right? Except for Chuck Norris.

**Comment by yashmehrotra** [comment]
Yeah, Chuck Norris doesn't count. The `offensive` category part is your call, IMO, the `offensive` doesn't harm anyone and similarly like adult jokes, they will only be returned when specified.

According to me, if anyone wants to get some `offensive` jokes, they shouldn't be offended.

**Comment by yashmehrotra** [comment]
@alexsavio Sorry, closed the issue by mistake.

**Comment by bennuttall** [comment]
With regard to jokes being offensive to a group (gender, ethnicity, etc.) this is fairly easy to distinguish, and determine what's unacceptable.

However, with regard to things like making fun of a programming language or other technology require a question of taste. For example jokes about it being hard to quite vim are fine, but jokes implying, for instance, that PHP is a bad language is more about the statement than the humour. Does that make sense?

We should number the rules so that we can say "violates rule 1", etc.

**Comment by yashmehrotra** [comment]
@bennuttall Yes that is indeed true. We do need a fine line that helps us decide which joke falls under which category.
But there are already jokes that sometimes make fun a language (imply that a language is bad) like `When your hammer is C++, everything begins to look like a thumb.` and `'Knock, knock.' 'Who’s there?' ... very long pause ... 'Java.'`

So unless until we come with a definite way of categorizing jokes, it comes down to personal opinion.

**Comment by alexsavio** [comment]
Well, this is called pyjokes, making fun of Java or C++ is not offending anyone, in reality we are just making fool of ourselves. Making fun of 'things' is not a problem, making fun of people is.

**Comment by alexsavio** [comment]
If someone feels so attached to C++, Java, Vim or even Python that they will be offended by this kind of jokes, that is their materialistic problem, not ours.

**Comment by yashmehrotra** [comment]
@alexsavio I agree with your point. Lets just say that the joke shouldn't be offensive to any person (based on religion, race etc.).
But jokes making fun of roles like QA, web designer , software engineer etc. should be accepted. What say ?

**Comment by alexsavio** [comment]
Well, while a war is not started because of job positions I guess it is alright if we don't respect them. Any suggestion @bennuttall ?

**Comment by bennuttall** [comment]
That sounds sensible. There's a line between gently poking fun at something (language, job position, text editor) and harshly singling it out negatively.

I'm going to push some guidelines into the CONTRIBUTING file and we can always add to and modify them.

**Comment by chirag127** [comment]
> * Racism should be avoided.

Well I think "must be avoided" would have been a better wording.
