### ISSUE TITLE
Consider removing programmer humour non-jokes

### ISSUE THREAD

**Issue by bennuttall** [pyjokes/pyjokes#22]
There seem to be a number of items in the jokes list which I wouldn't class as being *jokes*. They are humorous statements or even amusing pieces of code - but clearly these are not jokes.

Examples:

- `/* no comment */`
- `#define _(x) ((x) < score)`
- `tr { transform: rotate(180deg); }     It seems the tables have been turned.`
- `tabs > spaces`
- `spaces > tabs`

I don't want to be too strict but when using the module the behaviour is expected to be uniform. If there was a separate category for this type of humour that might help?

Any thoughts?

**Comment by yashmehrotra** [comment]
@bennuttall I agree with you, some jokes are best left in the source code .

**Comment by oiertwo** [comment]
I agree. Remove them.

**Comment by bennuttall** [comment]
TODO
