### ISSUE TITLE
General Jokes

### ISSUE THREAD

**Issue by ryanleesipes** [pyjokes/pyjokes#54]
The Mycroft project has built a skill that uses pyjokes for its joke repository.

I would like to propose that we add general joke support that include a wide range of jokes outside of programming centric. I would be happy to get this started if the pull request will be accepted.

**Comment by alexsavio** [comment]
That sounds cool! :)
@bennuttall could we leave the geek jokes as default and put new ones in other groups?

**Comment by ryanleesipes** [comment]
My thoughts is we leave the programming jokes as default and we make a group called "general" (or something like that).

**Comment by bennuttall** [comment]
Interesting. Do you have a source for jokes?

**Comment by ryanleesipes** [comment]
There are plenty of websites that we could pull from, if it all just needs to go into a flat text document, I could get someone on my team started on that.

**Comment by ryanleesipes** [comment]
To add on to that last point, right now it is all hardcoded into python files, we could pull those out into text files like "neutral.joke" (this is how we handle vocabulary and dialogue in Mycroft).

Otherwise, I can hit you with a pull request against the current english implementation with some general jokes (this seems like the fastest way to get stuff integrated right now).

**Comment by bennuttall** [comment]
Sorry this didn't go anywhwere, please reopen if there's something we can do now.
