### ISSUE TITLE
Dad jokes?

### ISSUE THREAD

**Issue by bildzeitung** [pyjokes/pyjokes#59]
I was wondering if it would be worth adding a category specifically for "dad" jokes, which is to say, a marker specifically for pun-based humour. I would add that this would create a bucket of the more difficult-to-translate items, as that sort of thing tends to be vocabulary-specific.

**Comment by oiertwo** [comment]
Hi, each language has its own jokes, some of them are translated but it is impossible to do it with all. So the translate-able problem is not a problem.

But i think that dad jokes fit perfectly in neutral jokes. So you can add some of them to the neutral list.

Thinking further maybe we need a _tag system_ to organize the jokes in each category... 

@bennuttall what do you think?

**Comment by bennuttall** [comment]
Would they be Dad programmer jokes? What about Mum jokes? I don't know

**Comment by oiertwo** [comment]
Good point of view. What about parents jokes?

**Comment by bennuttall** [comment]
I don't think these jokes are a fit for the library, closing this.

Miss you @oiertwo x
