### ISSUE TITLE
does this work in Windows?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [pyjokes/pyjokes#72]
related issue: https://github.com/pipxproject/pipx/issues/111

**Comment by bennuttall** [comment]
It should do - maybe it's an issue working with pipx (I'd not heard of this before). Do you know if it works if you `pip install` with Windows?

**Comment by Laurentiu-Andronache** [comment]
These guys sa it's a problem with pyjokes: https://github.com/pipxproject/pipx/issues/111#issuecomment-475469644

**Comment by bennuttall** [comment]
I'll change it to use entry points and do a new release when I get chance.

**Comment by GadgetSteve** [comment]
You can get it working from the command line on windows by adding a pyjoke.bat file in your python Scripts directory with the contents:

`@py C:/python36_64/Scripts/pyjoke` 

_Where python36_64 is my python scripts directory but yours is probably different._

**Comment by bennuttall** [comment]
v0.6.0 has been released and should work ok in Windows - can you confirm?

**Comment by GadgetSteve** [comment]
Works for me on Win10/64 python 3.7.4-64 but not with python 2.7.15/32 – the latter gives:
```
> c:\Python27\Scripts\pyjoke.exe
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\pyjoke.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\pyjokescli\pyjoke.py", line 3, in <module>
    from pyjokes import pyjokes
ImportError: cannot import name pyjokes
```
Steve

**Comment by GadgetSteve** [comment]
Tested with python 3.12-64, 3.11-64/32, 3.10-64 - all working OK! _(I no longer have access to any lower versions of python)._
