### ISSUE TITLE
How many jokes does this have?

### ISSUE THREAD

**Issue by Rishi-Bidani** [pyjokes/pyjokes#98]
Only if this has a decent amount of jokes will I consider using this. Maybe you should mention or at least give us an approximation in your documentation?

**Comment by elig0n** [comment]
```python
from pyjokes.pyjokes import all_jokes
for lang in all_jokes:
    print(lang, len(all_jokes[lang]['all']))
```

> en 200
de 146
es 14
gl 14
eu 5
it 159

I do agree that these numbers should be mentioned somewhere along the README or via a command line flag...
